import { getToolRegistry } from './ToolRegistry';
import { KnowledgeBaseSearchTool } from './KnowledgeBaseSearchTool';
import { ChatSummariesSearchTool } from './ChatSummariesSearchTool';
import { ChatMessagesSearchTool } from './ChatMessagesSearchTool';
import { KnowledgeBaseCountTool } from './KnowledgeBaseCountTool';
import { ChatSummariesCountTool } from './ChatSummariesCountTool';
import { KnowledgeBaseUpdatePageTool } from './KnowledgeBaseUpdatePageTool';
import { KnowledgeBaseDeletePageTool } from './KnowledgeBaseDeletePageTool';
import { KnowledgeBaseListPagesTool } from './KnowledgeBaseListPagesTool';
import { KnowledgeBaseGetPageTool } from './KnowledgeBaseGetPageTool';
import { KubectlListPodsTool } from './KubectlListPodsTool';
import { KubectlListNodesTool } from './KubectlListNodesTool';
import { KubectlDescribePodTool } from './KubectlDescribePodTool';
import { KubectlLogsTool } from './KubectlLogsTool';
import { KubectlGetEventsTool } from './KubectlGetEventsTool';
import { KubectlTopNodesTool } from './KubectlTopNodesTool';
import { KubectlTopPodsTool } from './KubectlTopPodsTool';
import { KubectlGetDeploymentsTool } from './KubectlGetDeploymentsTool';
import { KubectlRolloutStatusTool } from './KubectlRolloutStatusTool';
import { KubectlRolloutRestartTool } from './KubectlRolloutRestartTool';
import { KubectlGetServicesTool } from './KubectlGetServicesTool';
import { KubectlGetIngressesTool } from './KubectlGetIngressesTool';
import { KubectlApplyDryRunTool } from './KubectlApplyDryRunTool';
import { KubectlApplyTool } from './KubectlApplyTool';
import { KubectlDeletePodsTool } from './KubectlDeletePodsTool';
import { KubectlWaitDeleteTool } from './KubectlWaitDeleteTool';
import { KubectlGetPodsTool } from './KubectlGetPodsTool';
import { KubectlDeletePodTool } from './KubectlDeletePodTool';
import { LimaListInstancesTool } from './LimaListInstancesTool';
import { LimaInstanceStatusTool } from './LimaInstanceStatusTool';
import { LimaShellTool } from './LimaShellTool';
import { AgentGetSettingsTool } from './AgentGetSettingsTool';
import { AgentUpdateSettingsTool } from './AgentUpdateSettingsTool';
import { KubectlExecTool } from './KubectlExecTool';
import { KubectlCpFromPodTool } from './KubectlCpFromPodTool';
import { KubectlCpToPodTool } from './KubectlCpToPodTool';
import { KubectlGetPodYamlTool } from './KubectlGetPodYamlTool';
import { KubectlGetPodStatusTool } from './KubectlGetPodStatusTool';
import { HostListDirTool } from './HostListDirTool';
import { HostReadFileTool } from './HostReadFileTool';
import { HostTailFileTool } from './HostTailFileTool';
import { HostStatTool } from './HostStatTool';
import { HostFindFilesTool } from './HostFindFilesTool';
import { HostGrepTool } from './HostGrepTool';
import { HostRunCommandTool } from './HostRunCommandTool';
import { HostImageMetadataTool } from './HostImageMetadataTool';
import { EmitChatMessageTool } from './EmitChatMessageTool';
import { EmitChatImageTool } from './EmitChatImageTool';
import { CalendarListEventsTool } from './CalendarListEventsTool';
import { CalendarGetNextEventTool } from './CalendarGetNextEventTool';
import { CalendarGetEventTool } from './CalendarGetEventTool';
import { CalendarCreateEventTool } from './CalendarCreateEventTool';
import { CalendarUpdateEventTool } from './CalendarUpdateEventTool';
import { CalendarDeleteEventTool } from './CalendarDeleteEventTool';
import { SkillRunPluginTool } from './SkillRunPluginTool';
import { SkillListTool } from './SkillListTool';
import { SkillListEnabledTool } from './SkillListEnabledTool';
import { SkillInstallTool } from './SkillInstallTool';
import { SkillEnableTool } from './SkillEnableTool';
import { SkillDisableTool } from './SkillDisableTool';
import { ToolListTool } from './ToolListTool';

let registered = false;

export function registerDefaultTools(): void {
  const registry = getToolRegistry();

  const ensure = (tool: any) => {
    const name = String(tool?.name || '');
    if (!name) {
      return;
    }
    if (!registry.get(name)) {
      registry.register(tool);
    }
  };

  ensure(new KnowledgeBaseSearchTool());
  ensure(new ChatSummariesSearchTool());
  ensure(new ChatMessagesSearchTool());
  ensure(new KnowledgeBaseCountTool());
  ensure(new ChatSummariesCountTool());
  ensure(new KnowledgeBaseUpdatePageTool());
  ensure(new KnowledgeBaseDeletePageTool());
  ensure(new KnowledgeBaseListPagesTool());
  ensure(new KnowledgeBaseGetPageTool());
  ensure(new KubectlListPodsTool());
  ensure(new KubectlListNodesTool());
  ensure(new KubectlDescribePodTool());
  ensure(new KubectlLogsTool());
  ensure(new KubectlGetEventsTool());
  ensure(new KubectlTopNodesTool());
  ensure(new KubectlTopPodsTool());
  ensure(new KubectlGetDeploymentsTool());
  ensure(new KubectlRolloutStatusTool());
  ensure(new KubectlRolloutRestartTool());
  ensure(new KubectlGetServicesTool());
  ensure(new KubectlGetIngressesTool());
  ensure(new KubectlApplyDryRunTool());
  ensure(new KubectlApplyTool());
  ensure(new KubectlDeletePodsTool());
  ensure(new KubectlWaitDeleteTool());
  ensure(new KubectlGetPodsTool());
  ensure(new KubectlDeletePodTool());
  ensure(new LimaListInstancesTool());
  ensure(new LimaInstanceStatusTool());
  ensure(new LimaShellTool());
  ensure(new AgentGetSettingsTool());
  ensure(new AgentUpdateSettingsTool());
  ensure(new KubectlExecTool());
  ensure(new KubectlCpFromPodTool());
  ensure(new KubectlCpToPodTool());
  ensure(new KubectlGetPodYamlTool());
  ensure(new KubectlGetPodStatusTool());
  ensure(new HostListDirTool());
  ensure(new HostReadFileTool());
  ensure(new HostTailFileTool());
  ensure(new HostStatTool());
  ensure(new HostFindFilesTool());
  ensure(new HostGrepTool());
  ensure(new HostRunCommandTool());
  ensure(new HostImageMetadataTool());
  ensure(new ToolListTool());
  ensure(new SkillListTool());
  ensure(new SkillListEnabledTool());
  ensure(new SkillInstallTool());
  ensure(new SkillEnableTool());
  ensure(new SkillDisableTool());
  ensure(new SkillRunPluginTool());
  ensure(new EmitChatMessageTool());
  ensure(new EmitChatImageTool());
  ensure(new CalendarListEventsTool());
  ensure(new CalendarGetNextEventTool());
  ensure(new CalendarGetEventTool());
  ensure(new CalendarCreateEventTool());
  ensure(new CalendarUpdateEventTool());
  ensure(new CalendarDeleteEventTool());
  registered = true;
}

export { getToolRegistry } from './ToolRegistry';
export { BaseTool } from './BaseTool';
export { KnowledgeBaseSearchTool } from './KnowledgeBaseSearchTool';
export { ChatSummariesSearchTool } from './ChatSummariesSearchTool';
export { ChatMessagesSearchTool } from './ChatMessagesSearchTool';
export { KnowledgeBaseCountTool } from './KnowledgeBaseCountTool';
export { ChatSummariesCountTool } from './ChatSummariesCountTool';
export { KnowledgeBaseUpdatePageTool } from './KnowledgeBaseUpdatePageTool';
export { KnowledgeBaseDeletePageTool } from './KnowledgeBaseDeletePageTool';
export { KnowledgeBaseListPagesTool } from './KnowledgeBaseListPagesTool';
export { KnowledgeBaseGetPageTool } from './KnowledgeBaseGetPageTool';
export { KubectlListPodsTool } from './KubectlListPodsTool';
export { KubectlListNodesTool } from './KubectlListNodesTool';
export { KubectlDescribePodTool } from './KubectlDescribePodTool';
export { KubectlLogsTool } from './KubectlLogsTool';
export { KubectlGetEventsTool } from './KubectlGetEventsTool';
export { KubectlTopNodesTool } from './KubectlTopNodesTool';
export { KubectlTopPodsTool } from './KubectlTopPodsTool';
export { KubectlGetDeploymentsTool } from './KubectlGetDeploymentsTool';
export { KubectlRolloutStatusTool } from './KubectlRolloutStatusTool';
export { KubectlRolloutRestartTool } from './KubectlRolloutRestartTool';
export { KubectlGetServicesTool } from './KubectlGetServicesTool';
export { KubectlGetIngressesTool } from './KubectlGetIngressesTool';
export { KubectlApplyDryRunTool } from './KubectlApplyDryRunTool';
export { KubectlApplyTool } from './KubectlApplyTool';
export { LimaListInstancesTool } from './LimaListInstancesTool';
export { LimaInstanceStatusTool } from './LimaInstanceStatusTool';
export { LimaShellTool } from './LimaShellTool';
export { AgentGetSettingsTool } from './AgentGetSettingsTool';
export { AgentUpdateSettingsTool } from './AgentUpdateSettingsTool';
export { KubectlExecTool } from './KubectlExecTool';
export { KubectlCpFromPodTool } from './KubectlCpFromPodTool';
export { KubectlCpToPodTool } from './KubectlCpToPodTool';
export { KubectlGetPodYamlTool } from './KubectlGetPodYamlTool';
export { KubectlGetPodStatusTool } from './KubectlGetPodStatusTool';
export { HostListDirTool } from './HostListDirTool';
export { HostReadFileTool } from './HostReadFileTool';
export { HostTailFileTool } from './HostTailFileTool';
export { HostStatTool } from './HostStatTool';
export { HostFindFilesTool } from './HostFindFilesTool';
export { HostGrepTool } from './HostGrepTool';
export { HostRunCommandTool } from './HostRunCommandTool';
export { CalendarListEventsTool } from './CalendarListEventsTool';
export { CalendarGetNextEventTool } from './CalendarGetNextEventTool';
export { CalendarGetEventTool } from './CalendarGetEventTool';
export { CalendarCreateEventTool } from './CalendarCreateEventTool';
export { CalendarUpdateEventTool } from './CalendarUpdateEventTool';
export { CalendarDeleteEventTool } from './CalendarDeleteEventTool';
