export type Skill = {
  id: string;
  name: string;
  publisher: string;
  shortDescription: string;
  tags: string[];
  rating: number;
  activeInstalls: number;
  version: string;
  lastUpdated: string;
  icon?: string;
  banner?: string;
  commercial?: boolean;
  homepage?: string;
  authorUrl?: string;
  requires?: string;
  testedUpTo?: string;
  requiresPhp?: string;
  license?: string;
  licenseUrl?: string;
  downloads?: number;
  supportThreads?: number;
  advancedView?: string;
  overview?: string;
  installation?: string;
  changelog?: string;
  reviews?: string;
  support?: string;
  faq?: string;
  screenshots?: string;
};

export const skillsData: Skill[] = [
  {
    id: 'skill.sample.akismet',
    name: 'Akismet Anti-spam: Spam Protection',
    publisher: 'Automattic - Anti-spam Team',
    shortDescription: 'Used by millions, Akismet is quite possibly the best way in the world to protect your blog from spam.',
    tags:             ['anti-spam', 'comments', 'security'],
    rating:           4.7,
    activeInstalls:   5000000,
    version:          '5.3',
    lastUpdated:      'Recently',
    icon:             'https://ps.w.org/akismet/assets/icon-256x256.png',
    banner:           'https://ps.w.org/akismet/assets/banner-1544x500.jpg',
    commercial:       true,
    homepage:         'https://wordpress.org/plugins/akismet/',
    authorUrl:        'https://automattic.com/',
    requires:         '5.8',
    testedUpTo:       '6.5',
    requiresPhp:      '7.2',
    license:          'GPLv2 or later',
    licenseUrl:       'https://www.gnu.org/licenses/gpl-2.0.html',
    downloads:        350000000,
    supportThreads:   1200,
    overview:         'Akismet checks your comments and contact form submissions against our global database of spam to prevent your site from publishing malicious content.\n\nIt also includes a status history for each comment, so you can see which were caught or cleared by Akismet, and which were marked as spam or ham by a moderator.',
    installation:     '1. Install and activate the plugin.\n2. Click on the “Set up your Akismet account” button.\n3. Connect your site to an API key.\n4. Akismet will begin protecting your site immediately.',
    faq:              'Q: Do I need an Akismet account?\nA: Yes, you will need an API key to use Akismet.\n\nQ: Does Akismet work with contact forms?\nA: Yes, many form plugins integrate with Akismet, and Akismet can be configured to check form submissions.',
    screenshots:      '1. The Akismet settings screen.\n2. Comment status history.\n3. Spam statistics dashboard.',
    changelog:        '5.3: Performance improvements and compatibility updates.\n5.2: Improved spam detection.\n5.0: Major release with UI refresh.',
    reviews:          '“It just works. Huge reduction in spam.”\n\n“Easy setup and reliable.”',
    support:          'If you have questions, visit the support forum and include your WordPress version, PHP version, and any relevant logs.',
    advancedView:     'This is a sample plugin detail entry used to model the WordPress.org plugin detail layout inside Sulla. It is not actually installing Akismet.',
  },
  {
    id: 'skill.shell.git-cleanup',
    name: 'Git Cleanup',
    publisher: 'Sulla Labs',
    shortDescription: 'Cleans merged branches, prunes remotes, and keeps your repo tidy.',
    tags:             ['git', 'cleanup', 'repo'],
    rating:           4.8,
    activeInstalls:   18234,
    version:          '1.2.0',
    lastUpdated:      '2 days ago',
    overview:         'Git Cleanup helps keep local repositories healthy by removing merged branches, pruning stale tracking refs, and highlighting potentially dangerous deletes before they happen.',
    installation:     'Install the skill, then run it from the agent when you want to clean a repo. The skill will prompt before deleting branches.',
    changelog:        '1.2.0: Safer default branch detection.\n1.1.0: Added remote prune option.\n1.0.0: Initial release.',
    reviews:          'Solid and safe. Would love a dry-run mode toggle.\n- Community user',
    support:          'Open an issue with your repo state and the command output.',
  },
  {
    id: 'skill.k8s.context-switcher',
    name: 'Kube Context Switcher',
    publisher: 'Sulla Labs',
    shortDescription: 'Quickly list and switch kubecontexts with safety checks.',
    tags:             ['kubernetes', 'kubectl', 'safety'],
    rating:           4.7,
    activeInstalls:   9231,
    version:          '0.9.3',
    lastUpdated:      '1 week ago',
    overview:         'Lists kube contexts, highlights the current context, and switches contexts with an optional reachability check.',
    installation:     'Install the skill. It uses your existing kubeconfig and does not modify cluster resources.',
    changelog:        '0.9.3: Better error messages when kubeconfig is missing.\n0.9.0: Added reachability checks.',
    reviews:          'Makes switching clusters less scary.\n- Ops Toolkit',
    support:          'Provide your kubeconfig path and the failing context name.',
  },
  {
    id: 'skill.shell.node-version-audit',
    name: 'Node Version Audit',
    publisher: 'Community',
    shortDescription: 'Scans a project for engines fields, .nvmrc, and reports version drift.',
    tags:             ['node', 'audit', 'devex'],
    rating:           4.5,
    activeInstalls:   4410,
    version:          '0.4.1',
    lastUpdated:      '3 weeks ago',
    overview:         'Finds all the places a Node version is specified and flags mismatches so teams can standardize quickly.',
    installation:     'Install the skill, then run it inside a workspace folder.',
    changelog:        '0.4.1: Added pnpm support.\n0.4.0: Added packageManager parsing.',
    reviews:          'Caught our CI mismatch instantly.\n- Community user',
    support:          'Include the list of detected version files in your support request.',
  },
  {
    id: 'skill.shell.docker-disk-report',
    name: 'Docker Disk Report',
    publisher: 'Ops Toolkit',
    shortDescription: 'Reports container/image/volume disk usage and recommends safe cleanup commands.',
    tags:             ['docker', 'disk', 'ops'],
    rating:           4.6,
    activeInstalls:   12880,
    version:          '2.0.0',
    lastUpdated:      '5 days ago',
    overview:         'Summarizes disk usage across containers, images, and volumes and provides safe cleanup recommendations.',
    installation:     'Install the skill. Requires Docker CLI access on the host.',
    changelog:        '2.0.0: New report format.\n1.5.0: Added volume breakdown.',
    reviews:          'A must-have when dev machines start filling up.\n- Ops Toolkit',
    support:          'Attach the report output and your container engine info.',
  },
  {
    id: 'skill.shell.precommit-bootstrap',
    name: 'Pre-commit Bootstrap',
    publisher: 'Community',
    shortDescription: 'Bootstraps a pre-commit config and installs hooks for the current repo.',
    tags:             ['git', 'lint', 'automation'],
    rating:           4.3,
    activeInstalls:   2103,
    version:          '0.3.0',
    lastUpdated:      '1 month ago',
    overview:         'Creates a basic pre-commit configuration and installs hooks so linting happens on commit.',
    installation:     'Install the skill and run it from the root of a repo.',
    changelog:        '0.3.0: Adds default hook set.\n0.2.0: Handles existing configs.',
    reviews:          'Great starter setup.\n- Community user',
    support:          'Provide your repo type (language/framework) and the resulting config file.',
  },
  {
    id: 'skill.shell.ssh-agent-fix',
    name: 'SSH Agent Fix',
    publisher: 'Sulla Labs',
    shortDescription: 'Repairs common SSH agent issues and re-adds keys from your keychain.',
    tags:             ['ssh', 'security', 'macos'],
    rating:           4.4,
    activeInstalls:   7665,
    version:          '1.0.1',
    lastUpdated:      '6 days ago',
    overview:         'Resets and rehydrates your SSH agent session and verifies expected identities are loaded.',
    installation:     'Install the skill. macOS keychain integration is used when available.',
    changelog:        '1.0.1: Better error messages.\n1.0.0: Initial release.',
    reviews:          'Fixed my broken agent after an OS update.\n- Community user',
    support:          'Include ssh-agent env vars and ssh-add -l output.',
  },
  {
    id: 'skill.shell.terraform-fmt-all',
    name: 'Terraform Format All',
    publisher: 'Ops Toolkit',
    shortDescription: 'Runs terraform fmt recursively and summarizes changes.',
    tags:             ['terraform', 'iac', 'format'],
    rating:           4.2,
    activeInstalls:   3921,
    version:          '0.8.0',
    lastUpdated:      '2 weeks ago',
    overview:         'Recursively formats Terraform code and summarizes which files were changed.',
    installation:     'Install the skill. Requires terraform installed in PATH.',
    changelog:        '0.8.0: Adds summary output.\n0.7.0: Handles monorepos better.',
    reviews:          'Fast and simple.\n- Ops Toolkit',
    support:          'Include terraform version and the directory layout.',
  },
  {
    id: 'skill.shell.k9s-launcher',
    name: 'k9s Launcher',
    publisher: 'Community',
    shortDescription: 'Detects kubecontext, checks cluster reachability, then launches k9s.',
    tags:             ['kubernetes', 'k9s', 'tui'],
    rating:           4.1,
    activeInstalls:   1150,
    version:          '0.2.2',
    lastUpdated:      '4 days ago',
    overview:         'Runs preflight checks then launches k9s against the selected cluster context.',
    installation:     'Install the skill. Requires k9s installed in PATH.',
    changelog:        '0.2.2: Improves preflight failure messages.\n0.2.0: Adds context selection.',
    reviews:          'Nice UX for k9s launching.\n- Community user',
    support:          'Provide the context name and k9s version.',
  },
  {
    id: 'skill.shell.log-tailer',
    name: 'Smart Log Tailer',
    publisher: 'Sulla Labs',
    shortDescription: 'Tails logs with regex filters and automatic file rotation handling.',
    tags:             ['logs', 'debugging', 'cli'],
    rating:           4.6,
    activeInstalls:   8450,
    version:          '1.1.0',
    lastUpdated:      '1 day ago',
    overview:         'Tails one or more log files with optional regex filtering and handles rotation automatically.',
    installation:     'Install the skill and configure the file paths as inputs when prompted.',
    changelog:        '1.1.0: Adds rotation support.\n1.0.0: Initial release.',
    reviews:          'Rotation support is huge.\n- Sulla Labs user',
    support:          'Include example log lines and your filter expression.',
  },
  {
    id: 'skill.shell.secrets-scan',
    name: 'Secrets Scan',
    publisher: 'Security Guild',
    shortDescription: 'Scans a directory for common secret patterns and reports suspicious files.',
    tags:             ['security', 'scan', 'git'],
    rating:           4.0,
    activeInstalls:   990,
    version:          '0.1.0',
    lastUpdated:      '2 months ago',
    overview:         'Scans files for common token and credential patterns. It is heuristic-based and may produce false positives.',
    installation:     'Install and run against a directory. Review results manually before taking action.',
    changelog:        '0.1.0: Initial release.',
    reviews:          'Good baseline, but I want more detectors.\n- Security Guild user',
    support:          'Include the pattern category and a redacted sample that triggered it.',
  },
  {
    id: 'skill.shell.port-killer',
    name: 'Port Killer',
    publisher: 'Community',
    shortDescription: 'Finds and terminates the process listening on a port (with confirmation).',
    tags:             ['network', 'macos', 'debugging'],
    rating:           4.5,
    activeInstalls:   6032,
    version:          '1.0.0',
    lastUpdated:      '3 days ago',
    overview:         'Helps free up ports quickly by finding the owning PID and prompting before termination.',
    installation:     'Install the skill. Requires lsof on the host.',
    changelog:        '1.0.0: Initial release.',
    reviews:          'Saved me from hunting down processes manually.\n- Community user',
    support:          'Provide the port number and the process info output.',
  },
  {
    id: 'skill.shell.workspace-doctor',
    name: 'Workspace Doctor',
    publisher: 'Sulla Labs',
    shortDescription: 'Checks common project prerequisites and generates a quick fix report.',
    tags:             ['diagnostics', 'devex', 'automation'],
    rating:           4.7,
    activeInstalls:   13540,
    version:          '1.5.2',
    lastUpdated:      '1 week ago',
    overview:         'Runs a checklist of common prerequisites (tooling, environment vars, ports) and prints a human-readable report.',
    installation:     'Install the skill and run inside a project directory.',
    changelog:        '1.5.2: Adds report sections.\n1.5.0: Adds customizable checks.',
    reviews:          'Great onboarding tool for new engineers.\n- Sulla Labs',
    support:          'Include the generated report output and your OS version.',
  },
];
